import { buildDesignedModel } from './designed-archetypes.mjs';

const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export function primerCards(data,lane) {
  const byId=new Map(data.cards.map(c=>[c.id,c]));
  const preferred=lane.examples.map(name=>data.cards.find(c=>c.board==='mainboard'&&c.name===name)).filter(c=>c&&lane.pair.union.includes(c.id));
  const ranked=ids=>ids.map(id=>byId.get(id)).sort((a,b)=>(b.quality?.score||0)-(a.quality?.score||0));
  return [...new Map([...preferred,...ranked(lane.pair.payoffs),...ranked(lane.pair.enablers)].map(c=>[c.id,c])).values()].slice(0,3);
}
export function orderedPrimerLanes(data) {
  const lanes=buildDesignedModel(data).lanes;
  return [lanes[0],...lanes.slice(1).sort((a,b)=>b.pair.payoffs.length/Math.max(1,b.pair.pairPool)-a.pair.payoffs.length/Math.max(1,a.pair.pairPool))];
}
export function renderCubeCobraPrimer(data) {
  const lanes=orderedPrimerLanes(data);
  return [
    '# Winning in Style',
    'Big plays. Shared synergies. Flashy finishes.',
    'Born from Commander-style stories, played as a normal draft: no commanders required. Blink is the heart of the cube, with ten two-color starting points and room to branch out.',
    '**First draft?** [The visual five-minute guide](https://style.coolasheck.com/draft-primer.html) covers picks, removal, mana curve and your 40-card deck. [Cube health](https://style.coolasheck.com/) shows the exact support and intersections.',
    '## Your draft in four moves',
    '**Pick one, pass the rest.** Packs usually pass left, right, then left. Follow the host\'s pack setup.',
    '**Take removal seriously.** Efficient answers stop opposing engines and clear attacks. Balance them with creatures and a way to win.',
    '**Start with two colors.** Add a third only when your lands can cast it. Cards that support several plans keep your options open.',
    '**Build 40 cards.** Start near 17 lands, 15 creatures and 8 other spells. Removal is part of those spells, not extra cards. Adjust to your deck.',
    '## Two-color starting points',
    'Blink first; the remaining pairs are ordered by current in-pair payoff density, not a measured win-rate ranking. Every pair includes colorless support.',
    ...lanes.flatMap(lane=>[
      '### '+lane.colors.map(c=>'{'+c+'}').join('')+' '+lane.guild+' / '+lane.name,
      lane.plan,
      lane.id==='RG'?'Prioritize the threshold rewards, then early four-power bodies in red and green. Generic large creatures elsewhere are not proof of a healthy Gruul core.':'',
      lane.id==='UB'?'**'+lane.pair.enablers.length+' theft engines** in the core. These effects can win without separate theft-reward cards.':'**'+lane.pair.payoffs.length+' payoffs / '+lane.pair.enablers.length+' enablers** in the two-color core.',
      '<<'+primerCards(data,lane).map(c=>'[[!'+c.name+'|'+c.cardID+']]').join('')+'>>',
    ].filter(Boolean)),
    '## Keep the lanes open',
    'A card can do more than one job. Enter-the-battlefield creatures can bridge Blink into artifacts, counters or Humans. The health site keeps additional themes accessible without confusing them with the designed pairs.',
    'Choose a plan, draft enough early plays, pick answers, and make something worth remembering.',
  ].join('\n\n')+'\n';
}

export function renderDraftPrimer(data) {
  const lanes=orderedPrimerLanes(data);
  const image=c=>'<figure><img src="'+esc(c.image)+'" alt="'+esc(c.name)+'" loading="lazy"><figcaption>'+esc(c.name)+'</figcaption></figure>';
  const removal=['Swords to Plowshares','Lightning Bolt','Go for the Throat'].map(name=>data.cards.find(c=>c.board==='mainboard'&&c.name===name)).filter(Boolean);
  const blink=lanes[0];
  const blinkCards=['Phelia, Exuberant Shepherd','Overlord of the Mistmoors'].map(name=>data.cards.find(c=>c.board==='mainboard'&&c.name===name)).filter(Boolean);
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d0f11"><title>First Draft / Winning in Style</title><style>'+
    '*{box-sizing:border-box;letter-spacing:0}html{color-scheme:dark;-webkit-text-size-adjust:100%}body{margin:0;background:#0d0f11;color:#f5f7f8;font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main,header{max-width:900px;margin:auto;padding:20px max(20px,env(safe-area-inset-right)) 20px max(20px,env(safe-area-inset-left))}header{padding-top:max(16px,env(safe-area-inset-top));display:flex;justify-content:space-between;gap:12px;align-items:center}a{color:#79b8ff;min-height:44px;display:inline-flex;align-items:center}h1{font-size:30px;line-height:1.2;margin:0 0 12px}h2{font-size:21px;margin:0 0 10px}h3{font-size:17px;margin:0}p{margin:8px 0 16px;color:#c1c8cf}section{border-top:1px solid #343a40;padding:24px 0}small{color:#b3bdc6}.step{font-size:13px;color:#70c996;font-weight:700}.deck{display:grid;grid-template-columns:repeat(10,1fr);gap:5px;margin:16px 0}.deck i{aspect-ratio:5/7;border-radius:3px;background:var(--color)}.legend{display:flex;flex-wrap:wrap;gap:15px;font-size:14px}.legend i{display:inline-block;width:12px;height:12px;margin-right:6px;background:var(--color)}.picks{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.picks div{border-left:3px solid #79b8ff;padding-left:12px}.picks strong{font-size:22px;display:block;color:#f5f7f8}.gallery{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;max-width:650px}.gallery.blink{grid-template-columns:repeat(2,minmax(0,1fr));max-width:440px}figure{margin:8px 0;min-width:0}img{width:100%;aspect-ratio:488/680;object-fit:contain;border-radius:6px}figcaption{font-size:12px;line-height:1.4;color:#c1c8cf;margin-top:5px;overflow-wrap:anywhere}.curve{height:150px;display:grid;grid-template-columns:repeat(6,1fr);align-items:end;gap:12px;margin:16px 0}.curve div{height:100%;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:4px;font-size:13px}.curve i{width:100%;height:var(--height);background:#79b8ff;border-radius:3px 3px 0 0}details{border-top:1px solid #343a40}summary{min-height:56px;padding:14px 0;cursor:pointer;font-weight:700}summary span{color:#c1c8cf;font-weight:400}.pips{display:inline-flex;gap:3px;vertical-align:middle;margin-right:8px}.pips img{width:23px;height:23px;aspect-ratio:1;border-radius:50%}.checklist label{display:flex;gap:12px;align-items:center;min-height:48px}input{width:20px;height:20px;accent-color:#70c996}.callout{border-left:3px solid #e7b85b;padding-left:15px}.source-list a{font-size:13px;margin-right:16px}footer{border-top:1px solid #343a40;padding-top:18px;padding-bottom:max(20px,env(safe-area-inset-bottom))}a:focus-visible,summary:focus-visible{outline:2px solid #79b8ff;outline-offset:4px}@media(max-width:420px){h1{font-size:26px}.gallery{gap:8px}.picks{gap:8px}.picks div{padding-left:7px}.picks strong{font-size:19px}header{align-items:flex-start;flex-direction:column;gap:0}}'+
    '</style></head><body><header><strong>Winning in Style</strong><a href="./">Cube health &rarr;</a></header><main><h1>Your first cube draft</h1><p>Five minutes. One plan. A deck you can actually cast.</p>'+
    '<section><div class="step">01 / Pick and pass</div><h2>You build your deck as you go</h2><div class="picks"><div><small>PACK 1</small><strong>Pick 1</strong>Pass left &larr;</div><div><small>PACK 2</small><strong>Pick 1</strong>Pass right &rarr;</div><div><small>PACK 3</small><strong>Pick 1</strong>Pass left &larr;</div></div><p>Keep one card, pass the rest, then choose from the pack you receive. Repeat until the packs are empty. Follow the host\'s pack setup.</p><p>Start with strong, flexible cards. Settle into two colors as good cards keep coming. Your first pick is not a promise.</p></section>'+
    '<section><div class="step">02 / Answers matter</div><h2>Take good removal highly</h2><p class="callout"><strong>Removal</strong> gets a threat out of your way. It can stop their best engine or make your winning attack possible.</p><div class="gallery">'+removal.map(image).join('')+'</div><p>Prefer answers that are cheap and hit many threats. Do not spend your only answer on something harmless. You still need creatures and a way to win.</p></section>'+
    '<section><div class="step">03 / Build 40 cards</div><h2>A useful starting recipe</h2><div class="deck" role="img" aria-label="40 cards: 17 lands, 15 creatures, 8 other spells">'+Array.from({length:40},(_,i)=>'<i style="--color:'+(i<17?'#70c996':i<32?'#79b8ff':'#e7b85b')+'"></i>').join('')+'</div><div class="legend"><span><i style="--color:#70c996"></i>17 lands</span><span><i style="--color:#79b8ff"></i>15 creatures</span><span><i style="--color:#e7b85b"></i>8 other spells</span></div><p>Removal is inside the spell slots, not added on top. Some creatures are also removal. This is a starting point, not a quota.</p><p>Basic lands are provided; draft special lands that help cast your colors. Add a third color only with reliable mana support, not just one matching land.</p></section>'+
    '<section><div class="step">04 / Play on time</div><h2>More early plays. Fewer expensive cards.</h2><p><strong>Mana curve</strong> means how many cards you can play at each cost.</p><div class="curve" role="img" aria-label="Example 15-creature curve: one at 1 mana, five at 2, four at 3, three at 4, one at 5, one at 6 or more">'+[1,5,4,3,1,1].map((n,i)=>'<div><strong>'+n+'</strong><i style="--height:'+n*20+'px"></i><span>'+(i===5?'6+':i+1)+' mana</span></div>').join('')+'</div><p>One example for 15 creatures. Two- and three-mana plays help you attack or block before big cards arrive. A cheap combat trick is not a creature you can play early.</p></section>'+
    '<section><div class="step">05 / Pick a plan</div><h2>Blink is the heart of this cube</h2><p><strong>Payoff:</strong> rewards your plan. <strong>Enabler:</strong> makes it happen.</p><div class="gallery blink">'+blinkCards.map(image).join('')+'</div><p>Blink briefly exiles a permanent, then returns it. That can reuse an enter-the-battlefield reward. Check what the blink effect can target and when it returns.</p><p>Begin with a two-color core. These are starting points, not ten isolated decks.</p>'+
    lanes.map(l=>'<details '+(l.id==='WU'?'open':'')+'><summary><span class="pips">'+l.colors.map(c=>'<img src="assets/mana/'+c+'.svg" alt="'+({W:'White',U:'Blue',B:'Black',R:'Red',G:'Green'}[c])+'">').join('')+'</span>'+esc(l.guild)+' <span>/ '+esc(l.name)+'</span></summary><p>'+esc(l.plan)+'</p><div class="gallery">'+primerCards(data,l).map(image).join('')+'</div><a href="./?pair='+l.id+'">Explore '+esc(l.guild)+' support &rarr;</a></details>').join('')+'</section>'+
    '<section><h2>Before game one</h2><div class="checklist"><label><input type="checkbox">40 cards, including my lands</label><label><input type="checkbox">Enough early creatures or defensive plays</label><label><input type="checkbox">Answers to opposing threats</label><label><input type="checkbox">Lands that cast my main colors</label><label><input type="checkbox">A clear way to win</label></div><p>Ask a neighbor or the host for a deck check. Your unused drafted cards are your sideboard; swap them between games.</p></section>'+
    '<footer><details><summary>Sources and deeper reading</summary><div class="source-list"><a href="https://magic.wizards.com/en/formats/booster-draft">Wizards: draft rules</a><a href="https://magic.wizards.com/en/news/feature/how-build-mana-curve-2017-05-18">Wizards: mana curve</a><a href="https://magic.wizards.com/en/news/feature/signals-booster-draft-2015-01-19">Wizards: reading signals</a><a href="https://magic.wizards.com/en/news/feature/bloomburrow-prerelease-guide">Wizards: Limited deck building</a></div></details><small>Card examples verified in cube snapshot v'+data.cube.version+'. No commanders required.</small></footer></main></body></html>';
}
